version: '3.8'

services:
  web:
    build:
      context: ./src/server
      dockerfile: Dockerfile.dev
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./src/server/:/usr/src/app/
    ports:
      - "5001:5000"
    env_file:
      - ./src/server/.env.dev
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=thomas
      - POSTGRES_PASSWORD=thomas
      - POSTGRES_DB=thomas_le_boss

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


volumes:
  postgres_data: