name: torch
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - eigen=3.4.0
  - ffmpeg=4.2.2
  - filelock=3.9.0
  - fontconfig=2.13.94
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=68.2
  - idna=3.4
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libclang=12.0.0
  - libcurl=8.2.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm12=12.0.1
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libopus=1.3
  - libpng=1.6.39
  - libpq=12.15
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.25.2
  - numpy-base=1.25.2
  - opencv=4.6.0
  - openh264=1.8.0
  - openssl=3.1.3
  - packaging=23.1
  - pandas=2.0.3
  - patsy=0.5.3
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytorch=2.2.0.dev20230921
  - pytorch-model-summary=0.1.1
  - pytz=2023.3.post1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.2.2
  - scipy=1.11.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - statsmodels=0.14.0
  - sympy=1.11.1
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - torchaudio=2.2.0.dev20230921
  - torchvision=0.17.0.dev20230922
  - tornado=6.3.2
  - tqdm=4.66.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.38.4
  - x264=1!152.20180806
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - albumentations==1.3.1
      - anyio==4.0.0
      - appnope==0.1.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.4.0
      - async-lru==2.0.4
      - attrs==23.1.0
      - awscli==1.29.64
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - black==23.10.1
      - bleach==6.0.0
      - botocore==1.31.64
      - cachetools==5.3.2
      - click==8.1.7
      - colorama==0.4.4
      - comm==0.1.4
      - cython==3.0.6
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docutils==0.16
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - fqdn==1.5.1
      - google-auth==2.23.3
      - google-auth-oauthlib==1.1.0
      - grpcio==1.59.0
      - imageio==2.31.4
      - imgaug==0.4.0
      - ipykernel==6.25.2
      - ipython==8.16.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.0
      - jmespath==1.0.1
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.1
      - jupyter-console==6.6.3
      - jupyter-core==5.3.2
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - lazy-loader==0.3
      - markdown==3.5
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mouseinfo==0.1.3
      - mypy==1.7.1
      - mypy-extensions==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - notebook==7.0.4
      - notebook-shim==0.2.3
      - oauthlib==3.2.2
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.8.1.78
      - overrides==7.4.0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - patchify==0.2.3
      - pathspec==0.11.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.10.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.23.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyautogui==0.9.54
      - pygetwindow==0.0.9
      - pygments==2.16.1
      - pymsgbox==1.0.9
      - pyobjc-core==10.0
      - pyobjc-framework-cocoa==10.0
      - pyobjc-framework-quartz==10.0
      - pyperclip==1.8.2
      - pyrect==0.2.0
      - pyscreeze==0.1.30
      - python-json-logger==2.0.7
      - pytweening==1.0.7
      - pywavelets==1.4.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - qudida==0.0.4
      - referencing==0.30.2
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.3
      - rsa==4.7.2
      - rubicon-objc==0.4.7
      - s3transfer==0.7.0
      - scikit-image==0.21.0
      - screeninfo==0.8.1
      - send2trash==1.8.2
      - shapely==2.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.2
      - tensorboard==2.15.0
      - tensorboard-data-server==0.7.2
      - terminado==0.17.1
      - tifffile==2023.9.18
      - tinycss2==1.2.1
      - torchsummary==1.5.1
      - traitlets==5.10.1
      - types-colorama==0.4.15.12
      - types-pillow==10.1.0.2
      - types-pyautogui==0.9.3.7
      - types-pyscreeze==0.1.30.1
      - types-setuptools==69.0.0.0
      - types-tabulate==0.9.0.3
      - types-tqdm==4.66.0.5
      - uri-template==1.3.0
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
