name: torch_bis
channels:
  - defaults
dependencies:
  - python=3.11
  - torchaudio
  - torchvision
  - pytorch::pytorch
  - conda=23.11.0
  - albumentations
  - tqdm
  - screeninfo
  - matplotlib
  - einops
  - black
  - pytorch-model-summary
  - mypy_extensions
  - pip:
    - ema-pytorch==0.3.1
